# Generated by Django 2.2 on 2020-02-20 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reg_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('desc', models.TextField()),
                ('public', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sectors', to='reg_app.User')),
            ],
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('desc', models.TextField()),
                ('x_coord', models.IntegerField()),
                ('y_coord', models.IntegerField()),
                ('tag1', models.CharField(max_length=45)),
                ('tag2', models.CharField(max_length=45)),
                ('atmos', models.CharField(max_length=45)),
                ('temp', models.CharField(max_length=45)),
                ('biosphere', models.CharField(max_length=45)),
                ('population', models.CharField(max_length=45)),
                ('gravity', models.CharField(max_length=45)),
                ('techlevel', models.CharField(max_length=45)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='systems', to='swn_app.Sector')),
            ],
        ),
    ]
