# Generated by Django 2.2 on 2020-02-20 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swn_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='World',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, null=True)),
                ('desc', models.TextField(null=True)),
                ('x_coord', models.IntegerField()),
                ('y_coord', models.IntegerField()),
                ('tag1', models.CharField(max_length=45)),
                ('tag2', models.CharField(max_length=45)),
                ('atmosphere', models.CharField(max_length=45)),
                ('temperature', models.CharField(max_length=45)),
                ('biosphere', models.CharField(max_length=45)),
                ('population', models.CharField(max_length=45)),
                ('gravity', models.CharField(max_length=45)),
                ('techlevel', models.CharField(max_length=45)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='sector',
            name='desc',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='sector',
            name='name',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.DeleteModel(
            name='System',
        ),
        migrations.AddField(
            model_name='world',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='systems', to='swn_app.Sector'),
        ),
    ]
