# Generated by Django 2.2 on 2020-02-25 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swn_app', '0002_auto_20200220_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='world',
            name='map',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
