# Generated by Django 2.2 on 2020-02-25 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swn_app', '0003_world_map'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='world',
            name='map',
        ),
        migrations.AddField(
            model_name='sector',
            name='map',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
