# Generated by Django 2.2 on 2020-02-21 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reg_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='birthdate',
        ),
    ]
